<?php
$value = array (
  'wwwprefix' => 'http://www.dealuse.com',
  'imgprefix' => 'http://www.dealuse.com',
  'cssprefix' => 'http://www.dealuse.com',
  'sitename' => '优品会 - 温哥华团购网',
  'sitetitle' => '温哥华团购优惠好帮手',
  'abbreviation' => '优品会 - 温哥华团购网',
  'couponname' => '优品券',
  'currency' => '$',
  'currencyname' => 'CAD',
  'timezone' => 'Etc/GMT+8',
  'indexteam' => '10',
  'sideteam' => '10',
  'description' => '温哥华团购网 海外打折',
  'keywords' => '温哥华团购 优品会 精品打折团购',
  'invitecredit' => '0',
  'conduser' => 0,
  'partnerdown' => 0,
  'gzip' => 0,
  'kefuqq' => '',
  'kefumsn' => '',
  'mobileurl' => '',
  'icp' => '',
  'statcode' => '',
  'sinajiwai' => '',
  'tencentjiwai' => '',
  'googlemap' => '',
  'editor' => 'kind',
);
?>